accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import ExpDelete


app_name = 'accounts'


urlpatterns = [
    url(r"^settings/$",
        views.account_settings, name="account_settings"),
    url(r"^settings/(?P<username>[\w-]+)/$",
        views.company_settings, name="company_settings"),
    url(r'^remove_collaborator/$',
        views.remove_collab, name="remove_collab"),
    url(r"^experience/(?P<exp_pk>\d+)/edit/$",
        views.exp_edit, name="exp_edit"),
    url(r'^experience/(?P<exp_pk>\d+)/delete/$',
        ExpDelete.as_view(), name="exp_delete"),
]

jobs/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import Delete


app_name = 'jobs'


urlpatterns = [
    url(r"^(?P<company_pk>\d+)/create/$",
        views.create, name="create"),
    url(r"^(?P<job_pk>\d+)/apply/$",
        views.apply, name="apply"),
    url(r'^(?P<job_pk>\d+)/delete/$',
        Delete.as_view(), name="delete"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/$",
        views.detail, name="detail"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/edit/$",
        views.edit, name="edit"),
    url(r"^(?P<job_pk>\d+)/report/$",
        views.report, name="report"),
    url(r'^(?P<job_pk>\d+)/approve/$',
        views.accept_app_ajax, name='accept_app_ajax'),
    url(r'^(?P<job_pk>\d+)/reject/$',
        views.reject_app_ajax, name='reject_app_ajax'),
]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import (HttpResponseForbidden, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.cache import cache_page, never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.http import require_http_methods
from django.views.generic.edit import DeleteView

from activity.signals import activity_item
from core.decorators import account_type_required
from core.mixins import LoginRequiredMixin
from jobs.models import Job
from .forms import (AccountEmployerSettingsForm, AccountSettingsForm,
                    AddCollaboratorForm, CompanySettingsForm, ExperienceForm)
from .models import Company, Experience, MyUser

# Create your views here.


@login_required
def exp_edit(request, exp_pk):
    user = request.user
    exp = Experience.objects.get(pk=exp_pk)

    if user != exp.user:
        return HttpResponseForbidden()

    form = ExperienceForm(request.POST or None, instance=exp, user=user)

    if request.method == 'POST' and form.is_valid():
        form.save()
        messages.success(request,
                         "You have successfully updated your experience.")
        return redirect(user.get_absolute_url())

    context = {
        'form': form,
        'user': user
    }
    return render(request, 'accounts/exp_edit.html', context)


class ExpDelete(DeleteView, LoginRequiredMixin):
    model = Job
    success_message = "The experience was deleted."
    template_name = 'accounts/exp_delete.html'

    def get_object(self):
        _exp = Experience.objects.get(pk=self.kwargs['exp_pk'])
        if self.request.user != _exp.user:
            raise HttpResponseForbidden()
        return _exp

    def get_success_url(self):
        return reverse_lazy(self.request.user.get_absolute_url())

    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object,
        deletes the experience, and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(success_url)


@login_required
@cache_page(60 * 3)
def profile(request, username):
    try:
        # User Profile
        user = MyUser.objects.get(username=username)
        form = ExperienceForm(request.POST or None, instance=user, user=user)

        if request.method == 'POST':

            if form.is_valid():
                exp, created = Experience.objects.get_or_create(
                    user=user,
                    title=form.cleaned_data['title'],
                    company=form.cleaned_data['company'],
                    description=form.cleaned_data['description'],
                    date_start=form.cleaned_data['date_start'],
                    date_end=form.cleaned_data['date_end']
                )
                form.save()
                messages.success(request,
                                 "You have added an experience.")
            else:
                messages.error(request,
                               "There was an issue adding your experience.")

        context = {
            'experiences': Experience.objects.own(user=user),
            'form': form,
            'is_employer': user.account_type == MyUser.EMPLOYER,
            'user': user
        }
        template = 'accounts/profile.html'
    except MyUser.DoesNotExist:
        # Company profile
        company = get_object_or_404(
            Company, Q(is_active=True), username=username)
        _user_can_edit = False
        _is_company_collab = company.collaborators.filter(pk=request.user.pk)

        if company.user == request.user or _is_company_collab.exists():
            _user_can_edit = True

        jobs = Job.objects.own(company=company).filter(
            Q(list_date_start__lte=timezone.now()) &
            Q(list_date_end__gt=timezone.now())
        )

        context = {
            'company': company,
            'jobs': jobs,
            'user_can_edit': _user_can_edit
        }
        template = 'accounts/company_public.html'
    return render(request, template, context)


@login_required
@account_type_required
@never_cache
@sensitive_post_parameters()
def account_settings(request):
    user = get_object_or_404(MyUser, Q(is_active=True), pk=request.user.pk)

    if user.account_type == MyUser.STUDENT:  # Student account
        form = AccountSettingsForm(request.POST or None,
                                   request.FILES or None,
                                   instance=user, user=user)

        if request.method == 'POST':

            if form.is_valid():
                form.email = form.cleaned_data['email']
                form.username = form.cleaned_data['username']
                form.video = form.cleaned_data['video']
                form.undergrad_degree = form.cleaned_data['undergrad_degree']
                form.grad_degree = form.cleaned_data['grad_degree']
                password = form.cleaned_data['password_new_confirm']

                if password:
                    current_user = form.user
                    current_user.set_password(password)
                    current_user.save()
                    update_session_auth_hash(request, current_user)
                form.save()
                messages.success(request,
                                 "You have successfully updated your profile.")
            else:
                messages.error(request, "There was an error.")
    else:  # Company account
        form = AccountEmployerSettingsForm(request.POST or None,
                                           instance=user, user=user)

        if request.method == 'POST':

            if form.is_valid():
                form.email = form.cleaned_data['email']
                form.username = form.cleaned_data['username']
                password = form.cleaned_data['password_new_confirm']

                if password:
                    current_user = form.user
                    current_user.set_password(password)
                    current_user.save()
                    update_session_auth_hash(request, current_user)
                form.save()
                messages.success(request,
                                 "You have successfully updated your profile.")
            else:
                messages.error(request, "There was an error.")
    context = {
        'form': form,
        'is_employer': user.account_type == MyUser.EMPLOYER,
        'user': user
    }
    return render(request, 'accounts/settings.html', context)


@login_required
@require_http_methods(['POST'])
def remove_collab(request):
    company = get_object_or_404(Company, pk=request.POST.get('company_pk'))

    try:
        user = company.collaborators.get(pk=request.POST.get('user_pk'))
        company.collaborators.remove(user)
        user.account_type = None
        user.save(update_fields=['account_type'])
        activity_item.send(
            company,
            verb='Removed a collaborator.',
            target=user,
        )
    except ValueError:
        user = None
    return JsonResponse({})


@login_required
@never_cache
def company_settings(request, username):
    user = request.user
    company = get_object_or_404(Company, Q(is_active=True), username=username)
    _is_company_collab = company.collaborators.filter(pk=user.pk).exists()

    if (company.user == user or _is_company_collab and
            user.account_type == MyUser.EMPLOYER):

        form = CompanySettingsForm(request.POST or None,
                                   request.FILES or None,
                                   instance=company, company=company)
        collab_form = AddCollaboratorForm(request.POST or None)

        if request.method == 'POST':

            if form.is_valid():
                form.username = form.cleaned_data['username']
                form.save()
                messages.success(
                    request,
                    "You have successfully updated your company.")

            if collab_form.is_valid():
                email = collab_form.cleaned_data['email']

                if email:
                    if not company.collaborators.filter(email__iexact=email):
                        new_collab = MyUser.objects.filter(email__iexact=email)

                        if new_collab:
                            company.collaborators.add(new_collab[0])
                            new_collab[0].account_type = MyUser.EMPLOYER
                            new_collab[0].save(update_fields=['account_type'])
                            activity_item.send(
                                company,
                                verb='Added a collaborator.',
                                target=new_collab[0],
                            )
                            messages.success(
                                request,
                                "User has been added as a collaborator."
                            )
                        else:
                            messages.error(
                                request,
                                "That user does not exist on this website."
                            )
                    else:

templates/accounts/company_dash.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ company.name }} / Dashboard{% endblock title %}

{% block stylesheets %}
  <link href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <!-- top tiles -->
    <div class="row tile_count">
      <div class="col-md-4 col-sm-4 col-xs-12 tile_stats_count">
        <span class="count_top">
          <i class="fa fa-briefcase" aria-hidden="true"></i> Jobs Created
        </span>
        <div class="count">{{ jobs_count }}</div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 tile_stats_count">
        <span class="count_top">
          <i class="fa fa-briefcase" aria-hidden="true"></i> Active Jobs
        </span>
        <div class="count green">{{ active_job_count }}</div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 tile_stats_count">
        <span class="count_top">
          <i class="fa fa-user" aria-hidden="true"></i> Company Administrators
        </span>
        <div class="count">{{ collaborator_count }}</div>
      </div>
    </div>
    <!-- /top tiles -->
    <!-- jobs created table -->
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Jobs Created</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                <a href="{% url 'jobs:create' company.pk %}">
                  <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              The following jobs have been created by your company.
            </p>
            <table id="datatable" class="table table-striped jambo_table">
              <thead>
                <tr>
                  <th>Position</th>
                  <th>Location</th>
                  <th>Applicants</th>
                  <th>Active</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
               {% for job in jobs %}
                  <tr>
                    <td>
                      <a href="{{ job.get_absolute_url }}">{{ job.title }}</a>
                    </td>
                    <td>{{ job.location }}</td>
                    <td>{{ job.applicant_count }}</td>
                    <td>{{ job.is_active_job }}</td>
                    <td>
                      <a href="{{ job.get_absolute_url }}">
                        <i class="fa fa-search" aria-hidden="true"></i>
                      </a>
                      &nbsp;
                      <a href="{{ job.get_edit_url }}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                      </a>
                      &nbsp;
                      <a href="{{ job.get_delete_url }}">
                        <i class="fa fa-times" aria-hidden="true"></i>
                      </a>
                      &nbsp;
                      <a href="{{ job.get_report_url }}">
                        <i class="fa fa-bar-chart" aria-hidden="true"></i>
                      </a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- /jobs created table -->
    <div class="row">
        <!-- recent activity -->
        <div class="col-md-4 col-sm-4 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Recent Activity</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="dashboard-widget-content">
                {% if activity %}
                  <ul class="list-unstyled timeline widget">
                    {% for obj in activity %}
                      <li>
                        <div class="block">
                          <div class="block_content">
                            <h2 class="title">
                              {% if obj.target_object %}
                                <a href="{{ obj.get_target_url }}">
                                  {{ obj.target_object }}
                                </a>
                              {% endif %}
                            </h2>
                            <div class="byline">
                              <span>{{ obj.time_since }}</span>
                            </div>
                            <p class="excerpt">{{ obj }}</p>
                          </div>
                        </div>
                       </li>
                     {% endfor %}
                  </ul>
                {% else %}
                  <h4>No new activity.</h4>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- /recent activity -->
        <div class="col-md-8 col-sm-8 col-xs-12">
          <div class="row">
            <!-- collaborators -->
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>
                    Collaborators <small style="margin-left:0px;">of {{ company.name }}</small>
                  </h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li>
                      <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'accounts:company_settings' company.username %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <div class="col-md-6 col-sm-4 col-xs-12 profile_details">
                    <div class="card radius shadowDepth1">
                      <div class="card_image border-tlr-radius">
                        <img src="{% static 'img/default-profile-pic.jpg'%}" alt="Avatar" class="border-tlr-radius">
                      </div>
                      <div class="card_content card_padding">
                        <div class="card_share">
                          <div class="card_social">
                            <a class="share-icon mail" href="mailto:{{ company.user.email }}">
                              <span class="fa fa-envelope"></span>
                            </a>
                          </div>
                          <a id="share" class="share-toggle share-icon" href="#"></a>
                        </div>
                        <article class="card_article">
                          <h2>
                            {{ company.user.first_name }} {{ company.user.last_name }}
                          </h2>
                          <p>
                            <a href="mailto:{{ company.user.email }}">
                              <i class="fa fa-envelope-o" aria-hidden="true"></i> {{ company.user.email }}
                            </a>
                          </p>
                        </article>
                      </div>
                    </div>
                  </div>
                  {% for user in collaborators %}
                    <div class="col-md-6 col-sm-4 col-xs-12 profile_details">
                      <div class="card radius shadowDepth1">
                        <div class="card_image border-tlr-radius">
                          <img src="{% static 'img/default-profile-pic.jpg'%}" alt="Avatar" class="border-tlr-radius">
                        </div>
                        <div class="card_content card_padding">
                          <div class="card_share">
                            <div class="card_social">
                              <a class="share-icon mail" href="mailto:{{ user.email }}">
                                <span class="fa fa-envelope"></span>
                              </a>
                            </div>
                            <a id="share" class="share-toggle share-icon" href="#"></a>
                          </div>
                          <article class="card_article">
                            <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                            <p>
                              <a href="mailto:{{ user.email }}">
                                <i class="fa fa-envelope-o" aria-hidden="true"></i> {{ user.email }}
                              </a>
                            </p>
                          </article>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <!-- /collaborators -->
          </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
{% endblock js %}

{% block scripts %}
  <script>
    $(document).ready(function($) {
      $('#datatable').dataTable();

      $('.card_share > a').on('click', function(e) {
        e.preventDefault() // prevent default action - hash doesn't appear in url
        $(this).parent().find('div').toggleClass('card_social--active');
        $(this).toggleClass('share-expanded');
      });

    });
  </script>
{% endblock scripts %}

templates/accounts/company_settings.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}{{ company.name }} / Settings{% endblock title %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left"><h3>Company Settings</h3></div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <br/>
            <form action="." method="POST" enctype="multipart/form-data" role="form">
              {% csrf_token %}
              <fieldset>

                <div class="row">
                  <div class="form-group col-md-6 col-sm-6 col-xs-12 {% if form.name.errors %}has-error{% endif %}">
                    <label for="{{ form.name.auto_id }}" class="control-label">
                      {{ form.name.label }}
                    </label>
                    {{ form.name|add_class:"form-control" }}
                    {{ form.name.errors }}
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-md-6 col-sm-6 col-xs-12 {% if form.username.errors %}has-error{% endif %}">
                    <label for="{{ form.username.auto_id }}" class="control-label">
                      {{ form.username.label }}
                    </label>
                    {{ form.username|add_class:"form-control" }}
                    {{ form.username.errors }}
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-md-6 col-sm-6 col-xs-12 {% if form.logo.errors %}has-error{% endif %}">
                    <label for="{{ form.logo.auto_id }}" class="control-label">
                      {{ form.logo.label }}
                    </label>
                    {{ form.logo|add_class:"form-control" }}
                    {{ form.logo.errors }}
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-md-6 col-sm-6 col-xs-12 {% if form.website.errors %}has-error{% endif %}">
                    <label for="{{ form.website.auto_id }}" class="control-label">
                      {{ form.website.label }}
                    </label>
                    {{ form.website|add_class:"form-control" }}
                    {{ form.website.errors }}
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-md-6 col-sm-6 col-xs-12 {% if form.bio.errors %}has-error{% endif %}">
                    <label for="{{ form.bio.auto_id }}" class="control-label">
                      {{ form.bio.label }}
                    </label>
                    {{ form.bio|add_class:"form-control" }}
                    {{ form.bio.errors }}
                  </div>
                </div>

                <div class="row">
                  <div class="control-group col-md-6 col-sm-6 col-xs-12 {% if collab_form.email.errors %}has-error{% endif %}">
                    <label class="control-label">
                        Collaborators <small>(These users will have administrative access to your company.)</small>
                    </label>
                    <ul>
                      <li>
                        <p>
                            {{ company.user.get_full_name }},
                            {{ company.user.email }}
                        </p>
                      </li>
                      {% if company.collaborators %}
                        {% for obj in company.collaborators.all %}
                          <li>
                            <p>
                              {{ obj.get_full_name }},
                              {{ obj.email }}
                              {% if not obj == request.user %}
                                <a href="#" class="remove_collab_btn" data-user="{{ obj.pk }}" data-company="{{ company.pk }}">
                                  <i class="fa fa-times" style="margin-left:7px;" aria-hidden="true"></i>
                                </a>
                              {% endif %}
                            </p>
                          </li>
                        {% endfor %}
                      {% endif %}
                    </ul>
                    <a class="btn btn-default" data-toggle="modal" href="#addModal">
                      Add Collaborator
                    </a>
                    <!-- add collaborator modal -->
                    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-hidden="false" style="display:none;">
                      <div class="modal-dialog modal-md">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                              ×
                            </button>
                            <h4 class="modal-title">Add Collaborator</h4>
                          </div>
                          <div class="modal-body">
                            <label>Email</label>
                            <p>{{ collab_form.email }}</p>
                          </div>
                          <div class="modal-footer">
                            <button data-dismiss="modal" class="btn btn-default">
                              Close
                            </button>
                            <button class="btn btn-primary active" type="submit">
                              Add
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /add collaborator modal -->
                    {{ collab_form.email.errors }}
                  </div>
                </div>

                <div class="ln_solid"></div>
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <button id="submitButton" type="submit" class="btn btn-primary btn-block active">
                      Update
                    </button>
                  </div>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
    <br><br>
  </div>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            // Toggle form submit content when clicked
            var submitButton = $('#submitButton');

            submitButton.on('click', function() {
                // disable the button to prevent multiple submissions
                submitButton.attr('disabled', 'disabled').addClass('btn-disabled');
                submitButton.parents('form:first').submit();
            });

            $(".remove_collab_btn").click(function(e) {
                e.preventDefault();
                var a = $(e.target);
                $.ajax({
                    type: "POST",
                    url: "{% url 'accounts:remove_collab' %}",
                    data: {
                        user_pk: $(this).attr("data-user"),
                        company_pk: $(this).attr("data-company"),
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    },
                    dataType: "json",
                    success: function(e) {
                        window.location.href = window.location.href;
                    },
                    error: function() {
                        alert("Sorry, there was an error with your request. Please try again later.")
                    }
                })
            });
        });
    </script>
{% endblock scripts %}