accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import ExpDelete


app_name = 'accounts'


urlpatterns = [
    url(r"^settings/$",
        views.account_settings, name="account_settings"),
    url(r"^settings/(?P<username>[\w-]+)/$",
        views.company_settings, name="company_settings"),
    url(r'^remove_collaborator/$',
        views.remove_collab, name="remove_collab"),
    url(r"^experience/(?P<exp_pk>\d+)/edit/$",
        views.exp_edit, name="exp_edit"),
    url(r'^experience/(?P<exp_pk>\d+)/delete/$',
        ExpDelete.as_view(), name="exp_delete"),
]

authentication/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'authentication'


urlpatterns = [
    url(r"^authenticate/$",
        views.auth_login_register,
        name="auth_login_register"),
    url(r"^logout/$",
        views.auth_logout,
        name="auth_logout"),
    url(r"^password/reset/$",
        views.password_reset,
        name="password_reset"),
    url(r"^password/reset/confirm/"
        r"(?P<uidb64>[0-9A-Za-z_\-]+)/"
        r"(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.password_reset_confirm,
        name="password_reset_confirm"),
    url(r"^company/register/$",
        views.company_register,
        name="company_register"),
    url(r"^student/register/$",
        views.student_register,
        name="student_register"),
    url(r"^send_confirmation/$",
        views.send_confirmation,
        name="send_confirmation"),
    url(r"^confirm_account/"
        r"(?P<uidb64>[0-9A-Za-z_\-]+)/"
        r"(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.account_confirm,
        name="account_confirm"),
]

contact/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'contact'


urlpatterns = [
    url(r"^$", views.inquiry, name="inquiry"),
]

jobs/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import Delete


app_name = 'jobs'


urlpatterns = [
    url(r"^(?P<company_pk>\d+)/create/$",
        views.create, name="create"),
    url(r"^(?P<job_pk>\d+)/apply/$",
        views.apply, name="apply"),
    url(r'^(?P<job_pk>\d+)/delete/$',
        Delete.as_view(), name="delete"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/$",
        views.detail, name="detail"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/edit/$",
        views.edit, name="edit"),
    url(r"^(?P<job_pk>\d+)/report/$",
        views.report, name="report"),
    url(r'^(?P<job_pk>\d+)/approve/$',
        views.accept_app_ajax, name='accept_app_ajax'),
    url(r'^(?P<job_pk>\d+)/reject/$',
        views.reject_app_ajax, name='reject_app_ajax'),
]

templates/general/_sidebar.html
{% load staticfiles %}

<div class="col-md-3 left_col menu_fixed">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="{% url 'home' %}" class="site_title">
        <!-- <i class="fa fa-graduation-cap"></i> <span> KnobLinx</span> -->
        <img src="{% static 'img/knoblinx_logo.png' %}" style="width:90%;">
      </a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile">
      <div class="profile_pic">
        <a href="{{ request.user.get_absolute_url }}">
          <img class="img-circle profile_img" src="{{ request.user.user_profile_pic }}" alt="Profile icture" />
        </a>
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2>{{ request.user.first_name }}</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    <br/>
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div id="user-sidebar" class="menu_section" style="display:none;">
        <h3>General</h3>
        <ul class="nav side-menu">
          <li>
            <a href="{% url 'home' %}">
              <i class="fa fa-home" aria-hidden="true"></i> Home
            </a>
          </li>
          {% if not request.user.account_type == None %}
            <li>
              <a href="{{ request.user.get_absolute_url }}">
                <i class="fa fa-user" aria-hidden="true"></i> Profile
              </a>
            </li>
            <li>
              <a href="{% url 'accounts:account_settings' %}">
                <i class="fa fa-cog" aria-hidden="true"></i> Settings
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
      <div id="company-sidebar" class="menu_section" style="display:none;">
        <h3 class="company-name"></h3>
        <ul class="nav side-menu">
          <li>
            <a href="#" class="company-dash">
              <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
            </a>
          </li>
          <li>
            <a href="#" class="company-url">
              <i class="fa fa-user" aria-hidden="true"></i> Profile
            </a>
          </li>
          <li>
            <a href="#" class="company-settings">
              <i class="fa fa-tachometer" aria-hidden="true"></i> Settings
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

templates/general/_top_navigation.html
{% load staticfiles %}

<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="{{ request.user.user_profile_pic }}" alt="" />{{ request.user.get_full_name }}
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <a href="{% url 'accounts:account_settings' %}">Settings</a>
            </li>
            <li>
              <a href="{% url 'contact:inquiry' %}">Contact Us</a>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <a href="{% url 'authentication:auth_logout' %}">
                <i class="fa fa-sign-out pull-right"></i>Log Out
              </a>
            </li>
          </ul>
        </li>

        <!-- <li role="presentation" class="dropdown">
            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-bell"></i>
              <span class="badge bg-green">6</span>
            </a>
            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
              <li>
                <a>
                  <span class="image"><img src="#" alt="Profile Image" /></span>
                  <span>
                    <span>John Smith</span>
                    <span class="time">3 mins ago</span>
                  </span>
                  <span class="message">
                    Film festivals used to be do-or-die moments for movie makers. They were where...
                  </span>
                </a>
              </li>
              <li>
                <div class="text-center">
                  <a>
                    <strong>See All Alerts</strong>
                    <i class="fa fa-angle-right"></i>
                  </a>
                </div>
              </li>
            </ul>
        </li> -->

        <li class="">
          <a href="#" class="company-url" style="display:none;">
            <!-- <img id="company-logo" class="user-profile" style="border-radius:50%;width:29px;height:29px;" src="#" /> -->
            <span class="company-name"></span>
          </a>
        </li>

      </ul>
    </nav>
  </div>
</div>

templates/general/privacy_policy.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}KnobLinx / Privacy Policy{% endblock title %}

{% block content %}
  {% if not request.user.is_authenticated %}
    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="{% url 'home' %}" class="site_title">
            <img src="{% static 'img/knoblinx_logo.png' %}" style="width:90%;">
          </a>
        </div>
        <div class="clearfix"></div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div id="user-sidebar" class="menu_section">
            <ul class="nav side-menu">
              <li>
                <a href="{% url 'home' %}">
                  <i class="fa fa-home" aria-hidden="true"></i> Home
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left"><h3>Privacy Policy</h3></div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              Add content to the page ...
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/general/terms_of_use.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}KnobLinx / Terms of Use{% endblock title %}

{% block content %}
  {% if not request.user.is_authenticated %}
    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="{% url 'home' %}" class="site_title">
            <img src="{% static 'img/knoblinx_logo.png' %}" style="width:90%;">
          </a>
        </div>
        <div class="clearfix"></div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div id="user-sidebar" class="menu_section">
            <ul class="nav side-menu">
              <li>
                <a href="{% url 'home' %}">
                  <i class="fa fa-home" aria-hidden="true"></i> Home
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left"><h3>Terms of Use</h3></div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              Add content to the page ...
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}