accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import ExpDelete


app_name = 'accounts'


urlpatterns = [
    url(r"^settings/$",
        views.account_settings, name="account_settings"),
    url(r"^settings/(?P<username>[\w-]+)/$",
        views.company_settings, name="company_settings"),
    url(r'^remove_collaborator/$',
        views.remove_collab, name="remove_collab"),
    url(r"^experience/(?P<exp_pk>\d+)/edit/$",
        views.exp_edit, name="exp_edit"),
    url(r'^experience/(?P<exp_pk>\d+)/delete/$',
        ExpDelete.as_view(), name="exp_delete"),
]

jobs/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from .views import Delete


app_name = 'jobs'


urlpatterns = [
    url(r"^(?P<company_pk>\d+)/create/$",
        views.create, name="create"),
    url(r"^(?P<job_pk>\d+)/apply/$",
        views.apply, name="apply"),
    url(r'^(?P<job_pk>\d+)/delete/$',
        Delete.as_view(), name="delete"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/$",
        views.detail, name="detail"),
    url(r"^(?P<username>[\w.@+-]+)/(?P<job_pk>\d+)/edit/$",
        views.edit, name="edit"),
    url(r"^(?P<job_pk>\d+)/report/$",
        views.report, name="report"),
    url(r'^(?P<job_pk>\d+)/approve/$',
        views.accept_app_ajax, name='accept_app_ajax'),
    url(r'^(?P<job_pk>\d+)/reject/$',
        views.reject_app_ajax, name='reject_app_ajax'),
]

jobs/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from accounts.models import Company, Degree, School
from core.models import TimeStampedModel
from core.validators import validate_resume_ext
from .managers import ApplicantManager, JobManager

# Create your models here.


def get_resume_path(instance, filename):
    """
    Stores the resume in /applicant_resumes/username/filename.
    """
    return "/".join(['applicant_resumes', instance.user.username, filename])


@python_2_unicode_compatible
class Applicant(TimeStampedModel):
    PENDING = 0
    ACCEPTED = 1
    REJECTED = 2
    STATUS_TYPES = (
        (PENDING, _('Pending')),
        (ACCEPTED, _('Accepted')),
        (REJECTED, _('Rejected')),
    )
    status = models.IntegerField(choices=STATUS_TYPES, default=PENDING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    resume = models.FileField(upload_to=get_resume_path,
                              validators=[validate_resume_ext])
    email = models.EmailField(max_length=120)
    cover_letter = models.TextField(max_length=1000, blank=True)

    objects = ApplicantManager()

    class Meta:
        app_label = 'jobs'
        verbose_name = _('applicant')
        verbose_name_plural = _('applicants')

    def __str__(self):
        return str(self.user.get_full_name)

    @property
    def job_title(self):
        _job = Job.objects.get(applicants__pk=self.pk)
        return '{0} ({1})'.format(_job.title, _job.company.name)

    @cached_property
    def status_verbose(self):
        """
        Returns the verbose of the applicant's status.
        """
        return dict(Applicant.STATUS_TYPES)[self.status]


@python_2_unicode_compatible
class Job(TimeStampedModel):
    company = models.ForeignKey(Company,
                                related_name='job_owner',
                                on_delete=models.CASCADE)
    applicants = models.ManyToManyField(Applicant,
                                        related_name='job_applicants',
                                        blank=True)
    title = models.CharField(max_length=120)
    location = models.CharField(max_length=120)
    contact_email = models.EmailField(max_length=120, null=True)
    description = models.TextField(max_length=5000)
    min_gpa = models.DecimalField(_('Miniumum GPA'), max_digits=3,
                                  decimal_places=2, default=0.00)
    universities = models.ManyToManyField(School,
                                          related_name='job_universities')
    years = models.CharField(max_length=120)
    degrees = models.ManyToManyField(Degree, related_name='job_degrees')

    list_date_start = models.DateTimeField(_('Listing Start Date'), null=True)
    list_date_end = models.DateTimeField(_('Listing Expiration'), null=True)

    objects = JobManager()

    class Meta:
        app_label = 'jobs'
        verbose_name = _('job')
        verbose_name_plural = _('jobs')

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        """
        Returns the url for the job.
        """
        return reverse_lazy('jobs:detail',
                            kwargs={"job_pk": self.pk,
                                    "username": self.company.username})

    @property
    def get_edit_url(self):
        """
        Returns the edit url for the job.
        """
        return reverse_lazy('jobs:edit',
                            kwargs={"job_pk": self.pk,
                                    "username": self.company.username})

    @property
    def get_delete_url(self):
        """
        Returns the delete url for the job.
        """
        return reverse_lazy('jobs:delete', kwargs={"job_pk": self.pk})

    @property
    def get_report_url(self):
        """
        Returns the report url for the job.
        """
        return reverse_lazy('jobs:report', kwargs={"job_pk": self.pk})

    @cached_property
    def get_applicants_info(self):
        """
        Returns the information for each applicant as a list.
        """
        return self.applicants.values(
            'user__username', 'user__first_name', 'user__last_name',
            'user__profile_pic', 'user__email'
        )

    @property
    def applicant_count(self):
        """
        Returns the number of applicants for the job.
        """
        return self.get_applicants_info.count()

    @cached_property
    def get_universities_pk(self):
        """
        Returns a list of pks for the job's accepted universities.
        """
        return map(str, self.universities.values_list('pk', flat=True))

    @cached_property
    def get_degrees_pk(self):
        """
        Returns a list of pks for the job's accepted degrees.
        """
        return map(str, self.degrees.values_list('pk', flat=True))

    @cached_property
    def listing_start_date(self):
        """
        Returns the listing start date in the format: Month, day, year
        """
        return self.list_date_start.strftime("%B %d, %Y")

    @property
    def time_since(self):
        """
        Returns the time since the job has been posted.
        """
        return naturaltime(self.list_date_start)

    def is_active_job(self):
        start = self.list_date_start
        end = self.list_date_end
        return start <= timezone.now() and end >= timezone.now()
    is_active_job.boolean = True

jobs/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import (HttpResponseForbidden, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_http_methods
from django.views.generic.edit import DeleteView

from accounts.models import Company, MyUser
from activity.models import Activity
from activity.signals import activity_item
from core.decorators import account_type_required, user_is_company_collab
from core.mixins import LoginRequiredMixin
from .forms import ApplicantApplyForm, JobCreateForm
from .models import Applicant, Job

# Create your views here.


@login_required
@user_is_company_collab
@cache_page(60 * 3)
def report(request, job_pk):
    job = get_object_or_404(Job, pk=job_pk)
    years = []

    for year in MyUser.YEAR_TYPES:
        if str(year[0]) in job.years:
            years.append(str(year[1]))

    context = {
        'applicants': job.applicants.all().prefetch_related('user'),
        'domain': request.get_host(),
        'highest_degrees': MyUser.DEGREE_TYPES,
        'job': job,
        'opp_sought': MyUser.OPPORTUNITY_TYPES,
        'protocol': 'https' if request.is_secure() else 'http',
        'statuses': Applicant.STATUS_TYPES,
        'years': years
    }
    return render(request, 'jobs/report.html', context)


@login_required
@user_is_company_collab
@require_http_methods(['POST'])
def accept_app_ajax(request, job_pk):
    applicant = get_object_or_404(Applicant,
                                  pk=request.POST.get('app_pk'))
    applicant.status = Applicant.ACCEPTED
    applicant.save(update_fields=['status'])
    return JsonResponse({'new_status': applicant.status_verbose})


@login_required
@user_is_company_collab
@require_http_methods(['POST'])
def reject_app_ajax(request, job_pk):
    applicant = get_object_or_404(Applicant,
                                  pk=request.POST.get('app_pk'))
    applicant.status = Applicant.REJECTED
    applicant.save(update_fields=['status'])
    return JsonResponse({'new_status': applicant.status_verbose})


@login_required
@user_is_company_collab
def create(request, company_pk):
    user = request.user
    form = JobCreateForm(request.POST or None,
                         initial={'contact_email': user.email})

    if form.is_valid():
        new_job = Job.objects.create(
            user=user,
            company=Company.objects.get(pk=company_pk),
            title=form.cleaned_data['title'],
            location=form.cleaned_data['location'],
            contact_email=form.cleaned_data['contact_email'],
            min_gpa=form.cleaned_data['min_gpa'],
            universities=form.cleaned_data['universities'],
            years=form.cleaned_data['years'],
            degrees=form.cleaned_data['degrees'],
            list_date_start=form.cleaned_data['list_date_start'],
            list_date_end=form.cleaned_data['list_date_end'],
            description=form.cleaned_data['description']
        )
        messages.success(request, 'Your job has been created!')
        return HttpResponseRedirect(new_job.get_absolute_url())

    context = {
        'company': Company.objects.get(pk=company_pk),
        'form': form
    }
    return render(request, 'jobs/create.html', context)


@login_required
def apply(request, job_pk):
    user = request.user
    job = Job.objects.get(pk=job_pk)

    if not user.gpa:
        messages.error(request, 'Please add your GPA first.')
        return redirect('accounts:account_settings')
    elif not user.undergrad_uni:
        messages.error(request, 'Please add your university first.')
        return redirect('accounts:account_settings')
    elif not user.undergrad_degree:
        messages.error(request, 'Please add your degree first.')
        return redirect('accounts:account_settings')
    elif not user.is_confirmed:
        messages.error(request, 'Please confirm your account before applying.')
        return redirect('/')

    if not job.applicants.filter(user__pk=user.pk).exists():
        form = ApplicantApplyForm(request.POST or None,
                                  request.FILES or None,
                                  instance=user, user=user)

        if form.is_valid():
            applicant = Applicant.objects.create(
                user=user,
                resume=form.cleaned_data['resume'],
                email=form.cleaned_data['email'],
                cover_letter=form.cleaned_data['cover_letter']
            )
            job.applicants.add(applicant)
            messages.success(request, 'Thank you for applying!')
            return HttpResponseRedirect(job.get_absolute_url())

        context = {
            'form': form,
            'job': job,
            'user': user
        }
        return render(request, 'jobs/apply.html', context)
    return HttpResponseForbidden()


@login_required
@account_type_required
@cache_page(60 * 3)
def detail(request, job_pk, username):
    user = request.user
    job = get_object_or_404(Job, pk=job_pk)
    _is_company_collab = job.company.collaborators.filter(pk=user.pk).exists()
    can_del = True if job.company.user == user or _is_company_collab else False

    context = {
        'all_post_count': Job.objects.all().count(),
        'job': job,
        'recent_posts': Job.objects.recent()[:7],
        'viewer_can_delete': can_del,
        'viewer_has_applied': job.applicants.filter(user=request.user).exists()
    }
    return render(request, 'jobs/detail.html', context)


@login_required
@user_is_company_collab
def edit(request, username, job_pk):
    job = Job.objects.get(pk=job_pk)
    form = JobCreateForm(request.POST or None, instance=job)

    if form.is_valid():
        form.save()
        activity_item.send(
            job.company,
            verb='{0} edited the {1} job listing.'.format(
                request.user.get_full_name, job.title),
            target=job,
        )
        messages.success(request,
                         'Your job listing has been updated!')
        return HttpResponseRedirect(job.get_absolute_url())

    context = {
        'form': form,
        'job': job
    }
    return render(request, 'jobs/edit.html', context)


class Delete(DeleteView, LoginRequiredMixin):
    model = Job
    success_url = reverse_lazy('home')
    success_message = "The job has been deleted."
    template_name = 'jobs/delete.html'

    def get_object(self):
        user = self.request.user
        job = Job.objects.get(pk=self.kwargs['job_pk'])
        _is_company_collab = job.company.collaborators.filter(pk=user.pk)

        if job.company.user == user or _is_company_collab.exists():
            return job
        raise HttpResponseForbidden()

    def _delete_applicants(self):
        """
        Remove any previously set applicants for the instance.
        """
        self.object = self.get_object()
        self.object.applicants.clear()
        self.object.applicants.all().delete()

    def _delete_activity(self):
        """
        Remove any previously set activity for the instance.
        """
        Activity.objects.filter(target_object_id=self.get_object().id).delete()

    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object,
        deletes all applicants, and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        self._delete_applicants()  # Deletes applicants
        self._delete_activity()  # Deletes activity
        self.object.delete()  # Deletes the object
        activity_item.send(
            self.object.company,
            verb='{0} deleted the {1} job listing.'.format(
                request.user.get_full_name, self.object.title)
        )
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

templates/jobs/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}KnobLinx / Job Create{% endblock title %}

{% block stylesheets %}
  <link href="{% static 'vendors/bootstrap-daterangepicker/datetimepicker.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/bootstrap-wysiwyg/css/core-b3.css' %}" rel="stylesheet" />
  <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <form class="form-horizontal form-label-left" action="." method="POST" role="form">
                {% csrf_token %}
                <span class="section">Job Creation Form</span>

                <div class="item form-group {% if form.title.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.title.auto_id }}">
                    {{ form.title.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    {{ form.title }}
                    {{ form.title.errors }}
                  </div>
                </div>

                <div class="item form-group {% if form.location.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.location.auto_id }}">
                    {{ form.location.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    {{ form.location }}
                    {{ form.location.errors }}
                  </div>
                </div>

                <div class="item form-group {% if form.contact_email.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.contact_email.auto_id }}">
                    {{ form.contact_email.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    {{ form.contact_email }}
                    {{ form.contact_email.errors }}
                  </div>
                </div>

                <div class="item form-group {% if form.min_gpa.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.min_gpa.auto_id }}">
                    {{ form.min_gpa.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    {{ form.min_gpa }}
                    {{ form.min_gpa.errors }}
                  </div>
                </div>

                <br>

                <div class="item form-group {% if form.universities.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.universities.auto_id }}">
                    {{ form.universities.label }}
                  </label>
                  <div class="col-md-10 col-sm-10 col-xs-12" style="height:150px; overflow:auto;">
                    {% for choice in form.universities.field.choices %}
                      <input type="checkbox" name="universities" value="{{ choice.0 }}" class="flat" checked />
                      {{ choice.1 }}
                      <br>
                    {% endfor %}
                  </div>
                  <div class="control-label col-md-2 col-sm-2 col-xs-12"></div>
                  <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.universities.errors }}
                  </div>
                </div>

                <br>

                <div class="item form-group {% if form.years.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.years.auto_id }}">
                    {{ form.years.label }}
                  </label>
                  <div class="col-md-10 col-sm-10 col-xs-12" style="overflow:auto;">
                    {% for choice in form.years.field.choices %}
                      <input type="checkbox" name="years" value="{{ choice.0 }}" class="flat" checked />
                      {{ choice.1 }}
                      <br>
                    {% endfor %}
                    {{ form.years.errors }}
                  </div>
                </div>

                <br>

                <div class="item form-group {% if form.degrees.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.degrees.auto_id }}">
                    {{ form.degrees.label }}
                  </label>
                  <div class="col-md-10 col-sm-10 col-xs-12" style="height:150px; overflow:auto;">
                    {% for choice in form.degrees.field.choices %}
                      <input type="checkbox" name="degrees" value="{{ choice.0 }}" class="flat" />
                      {{ choice.1 }}
                      <br>
                    {% endfor %}
                  </div>
                  <div class="control-label col-md-2 col-sm-2 col-xs-12"></div>
                  <div class="col-md-10 col-sm-10 col-xs-12">
                      {{ form.degrees.errors }}
                  </div>
                </div>

                <br>

                <div class="item form-group {% if form.list_date_start.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.list_date_start.auto_id }}">
                    {{ form.list_date_start.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class='input-group date'>
                      {{ form.list_date_start }}
                      <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                      </span>
                    </div>
                      {{ form.list_date_start.errors }}
                  </div>
                </div>

                <div class="item form-group {% if form.list_date_end.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.list_date_end.auto_id }}">
                    {{ form.list_date_end.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class='input-group date'>
                      {{ form.list_date_end }}
                      <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                      </span>
                    </div>
                    {{ form.list_date_end.errors }}
                  </div>
                </div>

                <div class="item form-group {% if form.description.errors %}has-error{% endif %}">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="{{ form.description.auto_id }}">
                    {{ form.description.label }}
                  </label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class="panel panel-danger">
                      <div class="panel-body">{{ form.description }}</div>
                    </div>
                    {{ form.description.errors }}
                  </div>
                </div>
                <div class="ln_solid"></div>
                <button id="submitButton" type="submit" class="btn btn-block btn-success">
                  Create Job
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <br><br>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
  <script src="{% static 'custom/js/moment.min.js' %}"></script>
  <script src="{% static 'vendors/bootstrap-daterangepicker/datetimepicker.min.js' %}"></script>
  <script src="{% static 'vendors/bootstrap-wysiwyg/js/wysihtml5.js' %}" type="text/javascript"></script>
  <script src="{% static 'vendors/bootstrap-wysiwyg/js/core-b3.js' %}" type="text/javascript"></script>
{% endblock js %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function(){
            // Toggle form submit content when clicked
            var submitButton = $('#submitButton');
            submitButton.on('click', function(){
                // disable the button to prevent multiple submissions
                submitButton.attr('disabled', 'disabled').addClass('btn-disabled');
                submitButton.parents('form:first').submit();
            });

            var currentDate = new Date();
            $(function (){
                $('#id_list_date_start').datetimepicker({
                    defaultDate: currentDate,
                    sideBySide: true,
                });
            });
            $(function (){
                $('#id_list_date_end').datetimepicker({
                    defaultDate: currentDate.setDate(currentDate.getDate() + 21),
                    sideBySide: true,
                });
            });
            $(function(){ $(".textarea").wysihtml5(); });
        });
    </script>
{% endblock scripts %}

templates/jobs/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ job.company.name }} / Job {{ job.id }}{% endblock title %}

{% block stylesheets %}
  <link href="{% static 'custom/css/blog.min.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left"><h3>{{ job.title }}</h3></div>
        {% include 'search/_search_bar.html' %}
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-8">
          <div class="featured-post-wide">
              <img data-src="holder.js/1900x150/auto/#354458:#fff/text:{{ job.company.name }}" class="img-responsive" alt="Company">
              <div class="featured-text relative-left">
                <p class="additional-post-wrap">
                  <span class="additional-post">
                    <a href="{{ job.company.get_absolute_url }}">
                      <span class="label label-default square">
                        <i class="fa fa-user" aria-hidden="true"></i> {{ job.company.name }}
                      </span>
                    </a>
                  </span>
                  <span class="additional-post">
                    <span class="label label-default square">
                      <i class="fa fa-clock-o" aria-hidden="true"></i> {{ job.listing_start_date }}
                    </span>
                  </span>
                </p>
                {% if job.company.logo %}
                  <p style="text-align:center;">
                    <img src="{{ job.company.company_logo }}" class="img-rounded" style="height:100px;" alt="{{ job.company.name }}">
                  </p>
                {% endif %}
                <p>{{ job.description|safe }}</p>
                <hr>
                {% if viewer_has_applied %}
                  <button type="button" class="btn btn-block btn-warning" disabled="disabled">
                    Already Applied <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                  </button>
                {% elif viewer_can_delete %}
                  <a href="{{ job.get_delete_url }}" class="btn btn-danger active pull-right">
                    Delete Job
                  </a>
                  <a href="{{ job.get_edit_url }}" class="btn btn-info active">
                    Edit Job
                  </a>
                {% elif not user.gpa %}
                  <a href="{% url 'accounts:account_settings' %}" class="btn btn-info btn-block">
                    Add your GPA first <i class="fa fa-arrow-right" aria-hidden="true"></i>
                  </a>
                {% elif not user.undergrad_uni %}
                  <a href="{% url 'accounts:account_settings' %}" class="btn btn-info btn-block">
                    Add your university first <i class="fa fa-arrow-right" aria-hidden="true"></i>
                  </a>
                {% elif not user.undergrad_degree %}
                  <a href="{% url 'accounts:account_settings' %}" class="btn btn-info btn-block">
                    Add your degree first <i class="fa fa-arrow-right" aria-hidden="true"></i>
                  </a>
                {% elif not user.is_confirmed %}
                  <button type="button" class="btn btn-block btn-warning" disabled="disabled">
                    Please confirm your account first <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                  </button>
                {% else %}
                  <a href="{% url 'jobs:apply' job.pk %}" class="btn btn-success btn-block">
                    Apply For Position <i class="fa fa-check" aria-hidden="true"></i>
                  </a>
                {% endif %}
              </div>
            </div>
          </div>

          <!-- sidebar -->
          <div class="col-md-4">
            <div class="the-box">
              <h4 class="small-heading more-margin-bottom">
                RECENT LISTINGS <small>({{ all_post_count }} jobs created)</small>
              </h4>
              <hr>
              <ul class="media-list media-xs media-dotted">
                {% for post in recent_posts %}
                  <li class="media">
                    <small class="pull-right">{{ post.time_since }}</small>
                    <div class="media-body">
                      <a href="{{ post.company.get_absolute_url }}">
                        <small><em>{{ post.company.name }}</em></small>
                      </a>
                      <h4 class="media-heading">
                        <a href="{{ post.get_absolute_url }}">
                          {{ post.title }}
                        </a>
                      </h4>
                    </div>
                  </li>
                  {% if not forloop.last %}
                    <hr>
                  {% endif %}
                {% endfor %}
              </ul>
            </div>
          </div>
          <!-- /sidebar -->
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'vendors/holder/holder.js' %}" type="text/javascript"></script>
{% endblock js %}